// demo-场景案例/demo-flash-sale/ui-react/src/components/ListByMerchantId/index.jsx
import React, { Component } from 'react'
import styles from './index.module.css'
import axios from '../../api/axios'
import { message, Spin } from 'antd'

export default class ListByMerchantId extends Component {

  state = {
    orderList: [],
    queryStatus: '',
    loading: false,
    loadingText: "",
  }

  render() {
    return (
      <div className={styles.container}>
        <div className={styles.title}>商家查询订单列表</div>
        <div className={styles['operation-panel']}>
          <span>
            状态：
            <select value={this.state.queryStatus} onChange={(e) => {
              this.setState({ queryStatus: e.target.value })
            }}>
              <option value="">全部</option>
              <option value="Unpay">未支付</option>
              <option value="Undelivery">未发货</option>
              <option value="Unreceive">未收货</option>
              <option value="Received">已签收</option>
              <option value="Canceled">买家取消</option>
            </select>
          </span>
          <span>
            &nbsp;<button onClick={(e) => {
              let url;
              let status;
              if (this.state.queryStatus == '') {
                // 所有状态的订单
                url = "api/v1/order/listByMerchantIdAndWithoutStatus"
                status = null
              } else {
                url = "api/v1/order/listByMerchantIdAndStatus"
                status = this.state.queryStatus
              }

              this.setState({ loading: true, loadingText: "加载中..." })
              axios.get(url, {
                params: {
                  merchantId: localStorage.getItem("merchantId"),
                  latestMonth: true,
                  status: status
                }
              }).then((data) => {
                this.setState({ orderList: data })
              }).catch((error) => {
                message.error(error.errorMessage)
              }).finally(() => {
                this.setState({ loading: false, loadingText: "" })
              })
            }}>查询</button>
          </span>
        </div>
        <div className={styles['order-list-container']}>
          {
            this.state.orderList.length === 0 && (<div style={{ color: 'red' }}>没有订单信息</div>) ||
            this.state.orderList.map((item, index) => {
              return <div key={item.id}>
                <span>订单ID：{item.id}</span>
                ，<span>创建时间：{item.createTime}</span>
                ，<span>用户ID：{item.userId}</span>
                ，<span>
                  商品列表：
                  {
                    item.orderDetailList.map((detail, detailIndex) => {
                      return <React.Fragment key={detail.id}>
                        {detail.productName}，
                      </React.Fragment>
                    })
                  }
                </span>
              </div>
            })
          }
        </div>

        {
          // 操作中等待框
          this.state.loading && (<div
            style={{
              position: 'fixed',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              backgroundColor: 'rgba(0, 0, 0, 0.5)',
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              zIndex: 9999,
            }}
          >
            <Spin tip={this.state.loadingText}></Spin>
          </div>)
        }
      </div >
    )
  }
}

// demo-场景案例/demo-flash-sale/ui/src/components/ListByMerchantId.vue
<template>
    <div class="container">
        <div class="title">商家查询订单列表</div>
        <div class="operation-panel">
            <span>
                状态：
                <select v-model="queryStatus">
                    <option value="">全部</option>
                    <option value="Unpay">未支付</option>
                    <option value="Undelivery">未发货</option>
                    <option value="Unreceive">未收货</option>
                    <option value="Received">已签收</option>
                    <option value="Canceled">买家取消</option>
                </select>
            </span>
            <!-- <span>
                &nbsp;开始时间：<input type="text" size="10" />
            </span>
            <span>
                &nbsp;结束时间：<input type="text" size="10" />
            </span> -->
            <span>
                &nbsp;<button @click="handleClickQuery()">查询</button>
            </span>
        </div>
        <div class="order-list-container">
            <div v-for="item in this.orderList">
                <span>订单ID：{{ item.id }}</span>
                ，<span>创建时间：{{ item.createTime }}</span>
                ，<span>用户ID：{{ item.userId }}</span>
                ，<span>
                    商品列表：
                    <template v-for="detail in item.orderDetailList">
                        {{ detail.productName }}，
                    </template>
                </span>
            </div>
            <div v-if="this.orderList.length === 0" style="color:red;">没有订单信息</div>
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            queryStatus: '',
            orderList: [
                // {
                //     "id": 1944677143434874895,
                //     "userId": 1,
                //     "createTime": "2025-07-14 16:35:36",
                //     "status": {
                //         "name": "Undelivery",
                //         "description": "未发货"
                //     },
                //     "payTime": null,
                //     "deliveryTime": null,
                //     "receivedTime": null,
                //     "cancelTime": null,
                //     "deleteStatus": null,
                //     "merchantId": 2196861,
                //     "merchantName": null,
                //     "orderDetailList": [
                //         {
                //             "id": null,
                //             "orderId": 1944677143434874895,
                //             "productId": 19,
                //             "productName": null,
                //             "amount": 1
                //         }
                //     ]
                // }
            ]
        }
    },
    methods: {
        handleClickQuery() {
            let url;
            let status;
            if (this.queryStatus == '') {
                // 所有状态的订单
                url = "api/v1/order/listByMerchantIdAndWithoutStatus"
                status = null
            } else {
                url = "api/v1/order/listByMerchantIdAndStatus"
                status = this.queryStatus
            }

            const loading = this.$loading({
                lock: true,
                text: '加载中...',
                spinner: 'el-icon-loading',
                background: 'rgba(0, 0, 0, 0.7)'
            });
            this.$axios.get(url, {
                params: {
                    merchantId: localStorage.getItem("merchantId"),
                    latestMonth: true,
                    status: status
                }
            }).then((data) => {
                this.orderList = data
            }).catch((error) => {
                this.$message.error(error.errorMessage)
            }).finally(() => {
                loading.close()
            })
        }
    }
}
</script>

<style scoped>
.container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.title {
    margin-top: 10px;
}

.operation-panel {
    margin-top: 10px;
}

.order-list-container {
    margin-top: 10px;
}
</style>
